### ISSUE TITLE
脚本选项6. 修改 zhenxun_bot 配置文件点开后是cqhttp的配置文件

### ISSUE THREAD

**Issue by 0769559** [zhenxun-org/zhenxun_bot-deploy#1]
bug？：
脚本选项6. 修改 zhenxun_bot 配置文件点开后是cqhttp的配置文件

使用感想：
脚本傻瓜易容 还没奇怪的问题非常适合我这种复制粘贴选手，就是这默认插件全开 要挨个在qq用口令关闭有点难顶。

P站排行口令机器人永远是回复“网络不太好？没有该页数？也许过一会就好了...”   也不知道是不是个人问题还是插件问题。

要是有更多种类的bot一键部署脚本就更好了（小声

**Comment by AkashiCoin** [comment]
emmm，能跑就行，关于bug我会修复的，插件默认全开的话是bot那边的设置，p站排行的话得等bot那边修复才行

**Comment by AkashiCoin** [comment]
已修复
