### ISSUE TITLE
zhenxunbot和cqhttp能启动，device也替换了，但无法使用

### ISSUE THREAD

**Issue by TreesFeather** [zhenxun-org/zhenxun_bot-deploy#10]
![Screenshot_20220519_104825_com sonelli juicessh_edit_242330307433856](https://user-images.githubusercontent.com/105774046/169193775-6520c4ef-46c7-43c3-968c-29d1030cbe7f.jpg)
python版本是3.9，应该没问题的，请问应该怎么做？重装吗？谢谢大佬！

**Comment by ghost** [comment]
> 

输入7查看 go-cqhttp日志，然后扫码，试试能不能扫上。

**Comment by moe-lolicon** [comment]
登录成功了但是
![不知道是什么情况](https://pic1.rpgsky.net/img/moepic/2022/05/19/bee6d74b6fdc58b6532b6454b6a08ee7.png)

**Comment by ghost** [comment]
> 登录成功了但是 ![不知道是什么情况](https://camo.githubusercontent.com/9f68250bcebea153585a778d972dad130e00ee950c92a3486a93d87d2bebaddf/68747470733a2f2f706963312e727067736b792e6e65742f696d672f6d6f657069632f323032322f30352f31392f62656536643734623666646335386236353332623634353462366130386565372e706e67)

![image](https://user-images.githubusercontent.com/70250658/169254831-3bee1cdc-f010-40f8-b45e-eff991b24565.png)
检查一下zhenxun中的env.dev中的端口配置。
还是不行就全部重启go-cqhttp和zhenxun_bot

**Comment by ghost** [comment]
> > 登录成功了但是 ![不知道是什么情况](https://camo.githubusercontent.com/9f68250bcebea153585a778d972dad130e00ee950c92a3486a93d87d2bebaddf/68747470733a2f2f706963312e727067736b792e6e65742f696d672f6d6f657069632f323032322f30352f31392f62656536643734623666646335386236353332623634353462366130386565372e706e67)
> 
> ![image](https://user-images.githubusercontent.com/70250658/169254831-3bee1cdc-f010-40f8-b45e-eff991b24565.png) 检查一下zhenxun中的env.dev中的端口配置。 还是不行就全部重启go-cqhttp和zhenxun_bot

把localhost改成127.0.0.1试试

**Comment by moe-lolicon** [comment]
> > > 登录成功了但是 ![不知道是什么情况](https://camo.githubusercontent.com/9f68250bcebea153585a778d972dad130e00ee950c92a3486a93d87d2bebaddf/68747470733a2f2f706963312e727067736b792e6e65742f696d672f6d6f657069632f323032322f30352f31392f62656536643734623666646335386236353332623634353462366130386565372e706e67)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/70250658/169254831-3bee1cdc-f010-40f8-b45e-eff991b24565.png) 检查一下zhenxun中的env.dev中的端口配置。 还是不行就全部重启go-cqhttp和zhenxun_bot
> 
> 把localhost改成127.0.0.1试试

默认就是127.0.0.1
我把端口改成4089依旧如此

**Comment by ghost** [comment]
> > > > 登录成功了但是 ![不知道是什么情况](https://camo.githubusercontent.com/9f68250bcebea153585a778d972dad130e00ee950c92a3486a93d87d2bebaddf/68747470733a2f2f706963312e727067736b792e6e65742f696d672f6d6f657069632f323032322f30352f31392f62656536643734623666646335386236353332623634353462366130386565372e706e67)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/70250658/169254831-3bee1cdc-f010-40f8-b45e-eff991b24565.png) 检查一下zhenxun中的env.dev中的端口配置。 还是不行就全部重启go-cqhttp和zhenxun_bot
> > 
> > 
> > 把localhost改成127.0.0.1试试
> 
> 默认就是127.0.0.1 我把端口改成4089依旧如此

初次使用，先启动zhenxun再启动go-cqhttp。
