### ISSUE TITLE
提个install.sh的小建议

### ISSUE THREAD

**Issue by akademeia** [zhenxun-org/zhenxun_bot-deploy#12]
我是把install.sh作为整个bot的启动器来用，包括查看日志之类的，由于菜单里的8是卸载zhenxun_bot以及go-cqhttp，有一次想查看日志的时候手快按了个8回车，还没反应过来就给删的干干净净。这个卸载感觉可以换个数字，或者加一个二次确认，防止手贱。比如我是考虑把8改成789之类的

**Comment by AkashiCoin** [comment]
已改
