### ISSUE TITLE
脚本安装过程中报错“无法执行二进制文件 cannot execute binary file”

### ISSUE THREAD

**Issue by HAKURELING** [zhenxun-org/zhenxun_bot-deploy#3]
如题，系统是centos 7 x64
![image](https://user-images.githubusercontent.com/63252182/168828278-265720fb-4b69-46d1-b41a-29606e5076ce.png)

**Comment by xianyujunshigeCDD** [comment]
我也显示这个./go-cqhttp: ./go-cqhttp: cannot execute binary file 系统是centos 8 x64

**Comment by xianyujunshigeCDD** [comment]
> 我也显示了这个./go-cqhttp: ./go-cqhttp: 无法执行二进制文件 系统是centos 8 x64

![O(~HVZUZEQ~S)9 }C_J1_ U](https://user-images.githubusercontent.com/71781396/168830147-bb1c479c-e1ce-4515-a71d-b1cfa00bd23d.png)

**Comment by AkashiCoin** [comment]
更新了一下，大概可以用了？

**Comment by xianyujunshigeCDD** [comment]
> 更新了一下，大概可以用了？

![VM90NPZL{Y)I765C`A MDR7](https://user-images.githubusercontent.com/71781396/168851635-c39a2bae-8b9e-4319-8ce7-c3f70ee00f0a.png)

**Comment by xianyujunshigeCDD** [comment]
> 更新了一下，大概可以用了？

不过我看了一下确实是cq内核错了（

**Comment by HAKURELING** [comment]
QQ没办法扫码登录🤣,说是有风险
![Screenshot_2022-05-18-00-26-15-876_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/63252182/168861698-936993f7-316f-4751-930a-a97a8f11d6d8.jpg)

**Comment by xianyujunshigeCDD** [comment]
> 更新了一下，大概可以用了？
除了扫码报错还有这个 zhenxun打不开然后好像是缺环境？
![)}X8K 41N@@FQA F$97APLC](https://user-images.githubusercontent.com/71781396/168862249-a45f13fe-0efe-4e09-a63d-dc09396fdfda.png)

**Comment by HAKURELING** [comment]
> 更新了一下，大概可以用了？

好像无论如何都会触发登录验证？然后就提示不安全无法登录😂（刚注册的小号也会这样），有解决方法么![Screenshot_2022-05-18-00-26-15-876_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/63252182/168865388-5493f0f6-c8fb-4afc-88bc-0e0d9cf9a651.jpg)

**Comment by AkashiCoin** [comment]
> > 更新了一下，大概可以用了？
> 
> 好像无论如何都会触发登录验证？然后就提示不安全无法登录😂（刚注册的小号也会这样），有解决方法么![Screenshot_2022-05-18-00-26-15-876_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/63252182/168865388-5493f0f6-c8fb-4afc-88bc-0e0d9cf9a651.jpg)

在本地电脑上扫码登陆，然后把device.json和session.token两个文件上传到go-cqhttp的目录里，之后启动go-cq就行了
