### ISSUE TITLE
脚本中配置错误导致无法正常运行bot

### ISSUE THREAD

**Issue by GiGaFotress** [zhenxun-org/zhenxun_bot-deploy#33]
config.py中这个链接的写法是不是应该为postgres://
`sed -i 's|bind.*|bind: str = "postgresql://zhenxun:zxpassword@localhost:5432/zhenxun"|g' configs/config.py`

https://stackoverflow.com/questions/68887601/tortoise-exceptions-configurationerror-unknown-db-scheme-postgresql-error

**Comment by AkashiCoin** [comment]
是最近真寻那边更新的问题
