### ISSUE TITLE
这里的cqhttp安装不上 还有抽卡 Ubuntu20的系统

### ISSUE THREAD

**Issue by ayahana** [zhenxun-org/zhenxun_bot-deploy#4]
![image](https://user-images.githubusercontent.com/70086310/168858067-8e722ad5-afbe-4761-8a9b-900e3bd610b1.png)

**Comment by AkashiCoin** [comment]
注意用root权限运行，前面加个sudo

**Comment by ayahana** [comment]
多谢大佬 安装上了
