### ISSUE TITLE
安装完后识图的时候提示"Saucenao 缺失API_KEY！"

### ISSUE THREAD

**Issue by SuperPowerLF2** [zhenxun-org/zhenxun_bot-deploy#7]
能帮帮我吗(狗头

**Comment by ghost** [comment]
大佬，我试了下，也是。

**Comment by ghost** [comment]
Saucenao 缺失API_KEY！

**Comment by AkashiCoin** [comment]
修改真寻配置文件填入SN的API_KEY，相关链接在配置文件中有写

**Comment by ghost** [comment]
> 修改真寻配置文件填入SN的API_KEY，相关链接在配置文件中有写

好的，谢谢大佬，我去看看配置文件。

**Comment by CelicaEX** [comment]
请问这个API_KEY是填到哪里啊  看到文件夹里有   saucenao.py    __init__.py  两个文件  具体往什么位置填呢

**Comment by ghost** [comment]
> 请问这个API_KEY是填到哪里啊 看到文件夹里有 saucenao.py **init**.py 两个文件 具体往什么位置填呢

![image](https://user-images.githubusercontent.com/70250658/168983079-eba5d9fe-32e1-47f4-b024-c49fc4a48b9c.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/70250658/168983318-085d068b-1ed3-45e6-a7ea-f8d450fbe386.png)

**Comment by CelicaEX** [comment]
> ![image](https://user-images.githubusercontent.com/70250658/168983318-085d068b-1ed3-45e6-a7ea-f8d450fbe386.png)

感谢！！！！！原来是我一开始就搞错地方了..

**Comment by ghost** [comment]
> 

另外你知道修改配置文件config.yaml以后怎么快速重新启动，默认的命令是啥？不能每次都执行安装操作啊。

**Comment by CelicaEX** [comment]
> > 
> 
> 另外你知道修改配置文件config.yaml以后怎么快速重新启动，默认的命令是啥？不能每次都执行安装操作啊。

记得安装包的主菜单就有启动和停用的项目     ，已经没用这个一件安装版本了具体就不清楚了- 。  -
