### ISSUE TITLE
这个一键部署脚本要怎么用啊

### ISSUE THREAD

**Issue by Natsumelan** [zhenxun-org/zhenxun_bot-deploy#9]
大佬指点一下

**Comment by TreesFeather** [comment]
把它复制到命令行里，回车就可以了罢，我是用的linux系统云服务器。

**Comment by TreesFeather** [comment]
> 大佬指点一下

把它复制到终端里，回车就可以了罢，我用的是linux的云服务器（虽然登录这步还没搞）

**Comment by Natsumelan** [comment]
> > 大佬指点一下
> 
> 把它复制到终端里，回车就可以了罢，我用的是linux的云服务器（虽然登录这步还没搞）

使用install.sh下载真寻bot的时候闪退是怎么回事

**Comment by GUIskssw** [comment]
请问会了吗，我也是这样
